# These checks are run for PRs preparing a release
name: Release Check
on:
  pull_request:
    types:
      - opened
      - ready_for_review
    branches:
      - 'dev'
    paths:
      - 'changelog.txt' # To detect if this is a release PR
  workflow_dispatch:
jobs:
  check_manifest:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release-')
    steps:
      - name: Set line endings
        run: git config --global core.autocrlf true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update manifest
        run: python3 update_manifest.py --quiet --in-place
      - name: Check if the generated manifest is different
        run: git diff --exit-code manifest.xml
      - name: Check if the manifest version is correct
        run: |
          MANIFEST_VERSION=$(grep -o '<Version number="[^"]*' manifest.xml | sed 's/<Version number="//')
          BRANCH_VERSION=$(echo ${{ github.head_ref }} | sed 's/release-//')
          if [ "$MANIFEST_VERSION" != "$BRANCH_VERSION" ]; then
            echo "Manifest version ($MANIFEST_VERSION) does not match branch version ($BRANCH_VERSION)"
            exit 1
          fi
